# Generated by Django 4.1.7 on 2023-03-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRekord',
            new_name='AccessRecord',
        ),
    ]
